// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ougdnbsytiqbdocjagwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91Z2RuYnN5dGlxYmRvY2phZ3dlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMTc1MzYsImV4cCI6MjA2NDU5MzUzNn0.x8_rrLYAerC62JFqZwaf13QDOM6x_G9W7m8OboNGfaw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);